class AppError(Exception):
    def __init__(self, code: str, message: str, retry_after: int | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.retry_after = retry_after


class BadRequest(AppError): ...
class Unauthenticated(AppError): ...
class Forbidden(AppError): ...
class NotFound(AppError): ...
class Conflict(AppError): ...
class Unprocessable(AppError): ...
class UpstreamError(AppError): ...
